package Vista;
import Crud.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Leonardo
 */
public class VisualizarFrm extends javax.swing.JFrame{
    public static Icon PDF;
    //TableRowSorter trs; 
    //DefaultTableModel tm;
    //DefaultTableModel tdos;
    //Object[] o = new Object[6];
    //Object[] dt = new Object[6];
    


    public VisualizarFrm() {
        initComponents();
        PDF =new ImageIcon("src/Vista/pdf icon.png");
        mostrar();
        //dale();
        //tm = (DefaultTableModel) JtblListaProductos.getModel();
     
        
    }
//funcion rellenar tabla
    private void mostrar()
    {     
       Crud.CRUDproductos.Lista();
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JbtnPDF = new javax.swing.JButton();
        JbtnCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JcbxStock = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JcbxCategoria = new javax.swing.JComboBox<>();
        JcbxTamaño = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtblListaProductos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Visualizar Catalogo");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 255, 0));
        jPanel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JbtnPDF.setBackground(new java.awt.Color(255, 51, 51));
        JbtnPDF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JbtnPDF.setForeground(new java.awt.Color(255, 255, 255));
        JbtnPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/pdf icon.png"))); // NOI18N
        JbtnPDF.setText("Generar PDF");
        JbtnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnPDFActionPerformed(evt);
            }
        });
        jPanel1.add(JbtnPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 190, 60));

        JbtnCerrar.setBackground(new java.awt.Color(255, 102, 102));
        JbtnCerrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JbtnCerrar.setText("Cerrar");
        JbtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(JbtnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 670, 80, 30));

        jLabel1.setFont(new java.awt.Font("Roboto Slab Medium", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("STOCK");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 120, 100, 30));

        JcbxStock.setBackground(new java.awt.Color(255, 204, 51));
        JcbxStock.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        JcbxStock.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "Agotado" }));
        JcbxStock.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JcbxStockItemStateChanged(evt);
            }
        });
        JcbxStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcbxStockActionPerformed(evt);
            }
        });
        jPanel1.add(JcbxStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 150, 200, 40));

        jLabel2.setFont(new java.awt.Font("Roboto Slab Medium", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("CATEGORIA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 130, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Roboto Slab Medium", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("TAMAÑO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 100, 30));

        JcbxCategoria.setBackground(new java.awt.Color(255, 204, 51));
        JcbxCategoria.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        JcbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pizzas y Pasta", "Bebidas", "Piqueos", "Platos Criollos" }));
        JcbxCategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JcbxCategoriaItemStateChanged(evt);
            }
        });
        JcbxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcbxCategoriaActionPerformed(evt);
            }
        });
        JcbxCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JcbxCategoriaKeyTyped(evt);
            }
        });
        jPanel1.add(JcbxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 200, 40));

        JcbxTamaño.setBackground(new java.awt.Color(255, 204, 51));
        JcbxTamaño.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        JcbxTamaño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Familiar", "Mediana", "Personal" }));
        JcbxTamaño.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JcbxTamañoItemStateChanged(evt);
            }
        });
        JcbxTamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcbxTamañoActionPerformed(evt);
            }
        });
        jPanel1.add(JcbxTamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 200, 40));

        JtblListaProductos.setBackground(new java.awt.Color(255, 255, 204));
        JtblListaProductos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JtblListaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Categoria", "Tamaño", "Nombre", "Precio", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JtblListaProductos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 1010, 420));

        jLabel5.setFont(new java.awt.Font("Roboto Slab Medium", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("MENÚ PIZZAS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 290, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/pizzas.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 100, 90));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/paul pizza.png"))); // NOI18N
        jLabel7.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel7AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1250, 790));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JcbxStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcbxStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcbxStockActionPerformed

    private void JcbxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcbxCategoriaActionPerformed
      
    }//GEN-LAST:event_JcbxCategoriaActionPerformed

    private void JcbxTamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcbxTamañoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcbxTamañoActionPerformed

    private void jLabel7AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel7AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7AncestorAdded

    private void jPanel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel1AncestorAdded
  
    }//GEN-LAST:event_jPanel1AncestorAdded

    private void JcbxCategoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JcbxCategoriaKeyTyped
 
    }//GEN-LAST:event_JcbxCategoriaKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:  
    }//GEN-LAST:event_formWindowOpened
// TableRowSorter<DefaultTableModel> te=new TableRowSorter<DefaultTableModel>(tdos);
public static String Cat;
    private void JcbxCategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JcbxCategoriaItemStateChanged
        // TODO add your handling code here:

        Cat=JcbxCategoria.getSelectedItem().toString();
        Crud.CRUDproductos.FiltroCategoria();
            
    }//GEN-LAST:event_JcbxCategoriaItemStateChanged
public static String Sto;
    private void JcbxStockItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JcbxStockItemStateChanged

        Sto=JcbxStock.getSelectedItem().toString();
        Crud.CRUDproductos.FiltroStock();      
        
    }//GEN-LAST:event_JcbxStockItemStateChanged
public static String Tam;
    private void JcbxTamañoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JcbxTamañoItemStateChanged
        
        Tam=JcbxTamaño.getSelectedItem().toString();
        Crud.CRUDproductos.FiltroTamaño();
       
    }//GEN-LAST:event_JcbxTamañoItemStateChanged

    private void JbtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_JbtnCerrarActionPerformed

    private void JbtnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnPDFActionPerformed
        // TODO add your handling code here:
        Crud.CRUDproductos.PDFProductos();
      
    }//GEN-LAST:event_JbtnPDFActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnCerrar;
    private javax.swing.JButton JbtnPDF;
    public javax.swing.JComboBox<String> JcbxCategoria;
    public javax.swing.JComboBox<String> JcbxStock;
    public javax.swing.JComboBox<String> JcbxTamaño;
    public static javax.swing.JTable JtblListaProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
